#!/bin/bash
source port
source userpass
curl --url "http://127.0.0.1:$port" --data "{\"userpass\":\"$userpass\",\"method\":\"electrum\",\"coin\":\"BCH\",\"servers\":[{\"url\":\"electrum1.cipig.net:10055\"},{\"url\":\"electrum2.cipig.net:10055\"}], \"tx_history\":true}"
echo ""
curl --url "http://127.0.0.1:$port" --data "{\"userpass\":\"$userpass\",\"method\":\"electrum\",\"coin\":\"KMD\",\"servers\":[{\"url\":\"electrum1.cipig.net:10001\"},{\"url\":\"electrum2.cipig.net:10001\"}], \"tx_history\":true}"
echo ""
curl --url "http://127.0.0.1:$port" --data "{\"userpass\":\"$userpass\",\"method\":\"electrum\",\"coin\":\"LTC\",\"servers\":[{\"url\":\"electrum-ltc.bysh.me:50001\"},{\"url\":\"electrum.ltc.xurious.com:50001\"}], \"tx_history\":true}"
echo ""
curl --url "http://127.0.0.1:$port" --data "{\"userpass\":\"$userpass\",\"method\":\"electrum\",\"coin\":\"MORTY\",\"servers\":[{\"url\":\"electrum1.cipig.net:10018\"},{\"url\":\"electrum4.cipig.net:10018\"}], \"tx_history\":true}"
echo ""
curl --url "http://127.0.0.1:$port" --data "{\"userpass\":\"$userpass\",\"method\":\"electrum\",\"coin\":\"RICK\",\"servers\":[{\"url\":\"electrum1.cipig.net:10017\"},{\"url\":\"electrum4.cipig.net:10017\"}], \"tx_history\":true}"
echo ""
curl --url "http://127.0.0.1:$port" --data "{\"userpass\":\"$userpass\",\"method\":\"electrum\",\"coin\":\"DASH\",\"servers\":[{\"url\":\"electrum1.cipig.net:11061\"},{\"url\":\"electrum2.cipig.net:10061\"}], \"tx_history\":true}"
echo ""
curl --url "http://127.0.0.1:$port" --data "{\"userpass\":\"$userpass\",\"method\":\"electrum\",\"coin\":\"DOGE\",\"servers\":[{\"url\":\"electrum1.cipig.net:10060\"},{\"url\":\"electrum2.cipig.net:10060\"}], \"tx_history\":true}"
echo ""
curl --url "http://127.0.0.1:$port" --data "{\"userpass\":\"$userpass\",\"method\":\"electrum\",\"coin\":\"DGB\",\"servers\":[{\"url\":\"electrum1.cipig.net:10059\"},{\"url\":\"electrum2.cipig.net:10059\"}], \"tx_history\":true}"
echo ""
curl --url "http://127.0.0.1:$port" --data "{\"userpass\":\"$userpass\",\"method\":\"electrum\",\"coin\":\"KOIN\",\"servers\":[{\"url\":\"electrum1.cipig.net:10024\"},{\"url\":\"electrum2.cipig.net:10024\"}], \"tx_history\":true}"
echo ""
curl --url "http://127.0.0.1:$port" --data "{\"userpass\":\"$userpass\",\"method\":\"electrum\",\"coin\":\"ZEC\",\"servers\":[{\"url\":\"electrum1.cipig.net:10058\"},{\"url\":\"electrum2.cipig.net:10058\"}], \"tx_history\":true}"
echo ""
curl --url "http://127.0.0.1:$port" --data "{\"userpass\":\"$userpass\",\"method\":\"enable\",\"coin\":\"ETH\",\"urls\":[\"http://eth1.cipig.net:8555\"],\"swap_contract_address\":\"0x8500AFc0bc5214728082163326C2FF0C73f4a871\",\"gas_station_url\":\"https://ethgasstation.info/json/ethgasAPI.json\"}"
echo ""
curl --url "http://127.0.0.1:$port" --data "{\"userpass\":\"$userpass\",\"method\":\"enable\",\"coin\":\"MINDS\",\"urls\":[\"http://eth1.cipig.net:8555\"],\"swap_contract_address\":\"0x8500AFc0bc5214728082163326C2FF0C73f4a871\",\"gas_station_url\":\"https://ethgasstation.info/json/ethgasAPI.json\"}"
echo ""
